import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC


# Read the csv data as a DataFrame
df = pd.read_csv("telescope_data.csv", index_col=0)

# Remove null and na values
df.dropna()

# Print the DataFrame head
print(df.head())
class_columns = df['class']
data_matrix = df.drop(columns=['class'])

correlation_matrix = data_matrix.corr()
ax = plt.axes()
sns.heatmap(correlation_matrix, cmap='Greens', ax=ax)
ax.set_title('Correlation Matrix')
plt.show()


# ---------------
# Perform eigendecomposition.
# ---------------
eigenvalues, eigenvectors = np.linalg.eig(correlation_matrix)
print(f'Eigenvalues length: {eigenvalues.size}, Original Number of Features: {data_matrix.shape[1]}')

# Order the eigenvalues by ordering the indices of the eigenvalues
indices = eigenvalues.argsort()[::-1]  
eigenvalues = eigenvalues[indices]
eigenvectors = eigenvectors[:, indices]
print(eigenvalues.shape, eigenvectors.shape)

# Find the percentages of information for each eigenvector, which is generated by the proportion of its eigenvalues to the sum of all eigenvalues
information_proportions = eigenvalues / eigenvalues.sum()
print(f'Information Proportions: {information_proportions}')
information_percents = information_proportions * 100

# Plot the principal axes vs the information proportions for each principal axis
plt.figure()
plt.plot(information_percents, 'ro-', linewidth=2)
plt.title('Scree Plot')
plt.xlabel('Principal Axes')
plt.ylabel('Percent of Information Explained')
plt.show()

# Find the cumulative sum of the percentages
cumulative_information_percents = np.cumsum(information_percents)

# Plot the cumulative percentages array
plt.figure()
plt.plot(cumulative_information_percents, 'ro-', linewidth=2)
plt.title('Cumalative information')
plt.xlabel('Principal Axes')
plt.ylabel('Cumalative Infromation (%)')
plt.hlines(y=95, xmin=0, xmax=15)
plt.vlines(x=3, ymin=0, ymax=100)
plt.show()

# Creating standardised data matrix 
mean = np.mean(data_matrix)
stdd = np.std(data_matrix)

data_matrix_standardised = (data_matrix - mean) / stdd
# Using pca from sklearn 
pca = PCA()
pca.fit_transform(data_matrix_standardised)

singular_values = pca.singular_values_
print(f'Singular values: {singular_values}')

eigen_vectors = pca.components_.T
print(f'Eigen vectors: {eigen_vectors}')

variance_ratios = pca.explained_variance_
print(f'Variance Ratios: {variance_ratios}')

# PCA with two components
pca = PCA(n_components=2)
pca_results = pca.fit_transform(data_matrix_standardised)

df_pca = pd.DataFrame({
  'PC1': pca_results[:,0],
  'PC2': pca_results[:,1],
  'class': class_columns
})

sns.lmplot(x='PC1', y='PC2', data=df_pca, hue='class', fit_reg=False)

pca_1 = PCA(n_components=2) 

y = class_columns.astype('category').cat.codes
# Use the principal components as X and split the data into 33% testing and the rest training
X = pca_1.fit_transform(data_matrix_standardised) 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
 
# Create a Linear Support Vector Classifier
svc_1 = LinearSVC(random_state=0, tol=1e-5)
svc_1.fit(X_train, y_train) 
 
# Generate a score for the testing data
score_1 = svc_1.score(X_test, y_test)
print(f'Score for model with 2 PCA features: {score_1}')


# Using the original features 
# Select two features from the original data
first_two_original_features = [0, 1]
X_original = data_matrix_standardised.iloc[:, first_two_original_features]
 
# Split the data intro 33% testing and the rest training
X_train, X_test, y_train, y_test = train_test_split(X_original, y, test_size=0.33, random_state=42)
 
# Create a Linear Support Vector Classifier
svc_2 = LinearSVC(random_state=0)
svc_2.fit(X_train, y_train)
 
# Generate a score for the testing data
score_2 = svc_2.score(X_test, y_test)
print(f'Score for model with 2 original features: {score_2}')


